languages = {
    "en": "English",
    "zh_CN": "简体中文"
}

lang = {
    "en": {
        "settings": "Settings",
        "stop_and_quit": "Stop & Quit",
        "new_server": "New Server",
        "delete_server": "Delete Server",
        "delete_server_confirm": "Delete server?",
        "delete_server_confirm_description": "This action cannot be undone.",
        "prompt_confirm": "Confirm",
        "cancel": "Cancel",
        "save_changes": "Save Changes",
        "get_started": "Get Started",
        "prompt_done": "Done",
        "back": "Back",
        "help": "Help",
        "setting_language": "Language",
        "setting_background": "Keep running when closed",
        "setting_background_description": 'When enabled, the app will continue to run web servers in the background even when the window is closed. To stop the program while this option is enabled, click the "Stop & Quit" button.',
        "setting_updates": "Check for updates",
        "setting_updates_description": 'Periodically check if there is a new version of the app available. Updates are not automatically installed.',
        "setting_theme": "Appearance",
        "setting_theme_description": 'Change appearance (light/dark theme). By default the app follows your system theme.',
        "setting_theme_system": "Automatic (System)",
        "setting_theme_light": "Light",
        "setting_theme_dark": "Dark",
        "setting_plugins": "Plugins",
        "setting_plugins_description": 'Plugins allow you to further modify your web servers beyond the options that are available in the app. <a href="https://simplewebserver.org/docs/plugins.html">Learn more about plugins.</a><br><br>To install a plugin, click "Add Plugin" and then choose a directory or ZIP file. After installing a plugin, you must specifically enable it for each server you want to use it with.<br><br>Plugins aren\'t sandboxed, and run with the same permissions as the app. Only install a plugin if you know and trust the developer.',
        "add_plugin": "Add Plugin",
        "plugin_choose_folder": "Choose folder",
        "plugin_choose_zip": "Choose .zip file",
        "add_plugin_confirm": "Add \"[NAME]\" plugin?",
        "add_plugin_confirm_description": "Only install this plugin if you know and trust the developer.<br><br>Plugins aren't sandboxed, and run with the same permissions as the app.",
        "add_plugin_failed": "Failed to install plugin",
        "add_plugin_invalid": "Invalid plugin",
        "add_plugin_failed_description": "We couldn't find a valid <code>plugin.json</code> file in the directory or ZIP file you selected.",
        "remove_plugin": "Remove plugin",
        "remove_plugin_confirm": "Remove \"[NAME]\" plugin?",
        "remove_plugin_confirm_description": "All server options for this plugin will be cleared. If you want to update the plugin without resetting server options, just add the new version of the plugin instead of removing it first.",
        "edit_server": "Edit Server",
        "add_server": "Add Server",
        "create_server": "Create Server",
        "option_path": "Folder path",
        "option_path_description": 'Directory to serve files from. If the directory is within a hidden folder, then make sure to enable <a href="https://simplewebserver.org/docs/options.html#serve-hidden-dot-files">Serve hidden/dot files</a>.',
        "choose_folder": "Choose folder",
        "path_missing": "Please choose folder path",
        "option_port": "Port",
        "option_port_description": 'A number between 1 - 65535. Port that the local web server is accessible on. Access the website at <code>http://localhost:[PORT]</code>.',
        "port_invalid": "Enter a number between 1 and 65535",
        "port_in_use": "Port is already in use",
        "option_localnetwork": "Accessible on local network",
        "option_localnetwork_description": 'Makes the web server accessible over LAN to other computers on the network. Access it from another computer using the host computer\'s local IP address and the specified port. The LAN IP address will appear under web server URLs.<br><br>Enabling this option requires local network access. You may see a firewall permission prompt when enabling this option, and you must allow access in order for the web server to work over LAN.',
        "option_localnetwork_abbreviation": "LAN",
        "section_basic_rules": "Basic Rules",
        "option_showIndex": "Automatically show index.html",
        "option_showIndex_description": 'When no file path is specified, automatically serve <code>index.html</code> (if it exists).',
        "option_spa": "Single page rewrite (for SPAs)",
        "option_spa_description": 'Automatically rewrite all paths that don\'t exist to a single page. For <a href="https://developer.mozilla.org/en-US/docs/Glossary/SPA">Single Page Applications</a>.',
        "option_rewriteTo": "Rewrite to (for SPAs)",
        "option_rewriteTo_description": 'If the Single page rewrite option is enabled, specify what file to rewrite to. For <a href="https://developer.mozilla.org/en-US/docs/Glossary/SPA">Single Page Applications</a>.',
        "option_directoryListing": "Show directory listing",
        "option_directoryListing_description": 'Show a list of files in the specified directory instead of a 404 page.',
        "option_excludeDotHtml": "Exclude .html extension",
        "option_excludeDotHtml_description": 'Exclude .htm and .html extensions from URLs. For example, <code>/example.html</code> will redirect to <code>/example</code>. If a file exists at the path without an extension, the HTML file will still be rendered instead.',
        "section_advanced_rules": "Advanced Rules",
        "option_ipv6": "Listen on IPV6",
        "option_ipv6_description": 'Listen over IPV6 instead of the default, which is IPV4. This will change the web server URL(s) to be IPV6 instead of IPV4, however some IPV4 addresses will remain functional when LAN is enabled.',
        "option_ipv6_abbreviation": "IPV6",
        "option_cacheControl": "Cache-Control header value",
        "option_cacheControl_description": 'Optionally specify a custom <code>Cache-Control</code> HTTP header value. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control">Learn more about the Cache-Control header.</a>',
        "option_cors": "Set CORS headers",
        "option_cors_description": 'Allow cross origin requests. Sets <code>Access-Control-Allow-Origin</code> header to <code>*</code>, <code>Access-Control-Allow-Methods</code> to <code>GET, POST, PUT, DELETE</code>, and <code>Access-Control-Max-Age</code> to <code>120</code>. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS">Learn more about Cross-Origin Resource Sharing.</a>',
        "option_hiddenDotFiles": "Serve hidden/dot files",
        "option_hiddenDotFiles_description": 'Allow requesting hidden/dot files. These are files or folders with names that begin with a <code>.</code> character.',
        "option_upload": "Allow file upload",
        "option_upload_description": 'Allows PUT/POST requests. Includes hidden/dot files if they are enabled.',
        "option_replace": "Allow replacing files",
        "option_replace_description": 'If file upload is enabled, allows replacing files that already exist. Includes hidden/dot files if they are enabled.',
        "option_delete": "Allow deleting files",
        "option_delete_description": 'Allows DELETE requests. Includes hidden/dot files if they are enabled.',
        "option_staticDirectoryListing": "Always use static directory listing",
        "option_staticDirectoryListing_description": 'Disables JavaScript enhancement of the directory listing page.',
        "option_hiddenDotFilesDirectoryListing": "Show hidden/dot files in directory listing",
        "option_hiddenDotFilesDirectoryListing_description": 'If hidden/dot files are enabled, determines if they will additionally be shown in the directory listing. This includes <code>.swshtaccess</code> files.',
        "option_htaccess": "Enable .swshtaccess configuration files",
        "option_htaccess_description": 'You can use <code>.swshtaccess</code> files to set additional rules on a per-directory basis. See <a href="https://simplewebserver.org/docs/swsaccess.html">Advanced configuration using .swshtaccess files</a>.<br><br>This functionality is experimental and may change in future releases. Consider using <a href="https://simplewebserver.org/docs/plugins.html">plugins</a> instead.',
        "section_error_pages": "Error Pages",
        "option_custom404": "Custom 404 page file path",
        "option_custom404_description": 'File path to a custom 404 page. Will fallback to a generic 404 page if this value is empty or specified path is not valid.',
        "option_custom403": "Custom 403 page file path",
        "option_custom403_description": 'File path to a custom 403 page. Will fallback to a generic 403 page if this value is empty or specified path is not valid.',
        "option_custom401": "Custom 401 page file path",
        "option_custom401_description": 'File path to a custom 401 page. Will fallback to a generic 401 page if this value is empty or specified path is not valid.',
        "option_customErrorReplaceString": "Custom error path variable",
        "option_customErrorReplaceString_description": 'Optionally specify a custom string that will be looked for in your error pages and replaced with the current path. For example, if your custom 404 page included: <code>The file at {{PATH}} does not exist</code> and you set this option to <code>{{PATH}}</code>, when your custom page is served it would say <code>The file at /example.txt does not exist</code>.',
        "section_security": "Security",
        "option_https": "Use HTTPS",
        "option_https_description": 'Make server accessible over a secure connection (https) instead of http. Uses the same single port, so you cannot use both http and https at the same time. See <a href="https://simplewebserver.org/docs/https.html">Using HTTPS</a>.',
        "option_https_abbreviation": "HTTPS",
        "option_httpsCert": "SSL/TLS cerificate",
        "option_httpsCert_description": 'Optionally override this option to provide a custom HTTPS certificate. See <a href="https://simplewebserver.org/docs/https.html">Using HTTPS</a>.',
        "option_httpsKey": "SSL/TLS private key",
        "option_httpsKey_description": 'Optionally override this option to provide a custom HTTPS private key. See <a href="https://simplewebserver.org/docs/https.html">Using HTTPS</a>.',
        "generate_crypto": "Generate dummy cert",
        "generate_crypto_overwrite": "Overwrite certificate and private key?",
        "generate_crypto_overwrite_description": "A certificate and private key already exist. This action will overwrite them.",
        "option_httpAuth": "Enable HTTP Basic authentication",
        "option_httpAuth_description": 'Require authentication using the HTTP Basic authentication protocol. Specify a username and password in the HTTP Basic auth username and HTTP Basic auth password options. If either the username or password option is missing or invalid, the web server will become inaccessible.',
        "option_httpAuthUsername": "HTTP Basic auth username",
        "option_httpAuthUsername_description": 'Username for HTTP Basic authentication. Cannot contain a colon (<code>:</code>) character.',
        "httpAuthUsername_invalid": "Username cannot contain \":\"",
        "option_httpAuthPassword": "HTTP Basic auth password",
        "option_httpAuthPassword_description": 'Password for HTTP Basic authentication. Stored in plain text.',
        "option_ipThrottling": "Maximum connections per IP address",
        "option_ipThrottling_description": 'Limits the number of incoming connections per IP address. Set to 0 for unlimited connections.',
        "ipThrottling_invalid": "Enter a number greater than or equal to 0",
        "state_stopped": "Stopped",
        "state_starting": "Starting...",
        "state_running": "Running",
        "state_error": "Error",
        "update_available": "An updated version of Simple Web Server is available",
        "enabled_switch": "Enabled",
        "no_servers": "You haven't created any servers yet",
        "error_port_in_use": "Port in use",
        "error_port_in_use_description": "Web server failed to start because port [PORT] is already in use by another program.",
        "error_file_system": "File system error",
        "error_plugins": "Error starting plugins",
        "error_generic": "Error",
        "version": "Version",
        "documentation": "Documentation",
        "issues_and_suggestions": "Issues & Suggestions"
    },
    "zh_CN": {
        "new_server": "新服务器"
    }
}